FROM node:22-bookworm-slim

WORKDIR /workspace

COPY package*.json ./
RUN npm ci --ignore-scripts

COPY tsconfig.json cucumber.js ./
COPY api ./api
COPY core ./core
COPY utils ./utils
COPY scripts ./scripts

ENV API_BASE_URL=http://api-mock:4010

CMD ["npm", "run", "test:api"]