/** Page object for opening an additional bank account and reading its balance. */
import { BasePage } from "./BasePage";
import { Locator, Page,expect } from "@playwright/test";

export class OpenNewAccountPage extends BasePage {

    readonly openAccountLink: Locator;
    readonly accountType: Locator;
    readonly fromAccount: Locator;
    readonly openAccountButton: Locator;
    readonly accountsuccessMessage: Locator;
    readonly accountNumber: Locator;
    readonly accountoverviewLink: Locator;

    constructor(page:Page) {
        super(page);
        this.openAccountLink = page.getByRole('link', { name: 'Open New Account' });
        this.accountType = page.locator('#type');
        this.fromAccount = page.locator('#fromAccountId');
        this.openAccountButton = page.getByRole('button', { name: 'Open New Account' });
        this.accountsuccessMessage = page.getByRole('heading', { name: 'Account Opened!' });
        this.accountNumber = page.locator('#newAccountId');
        this.accountoverviewLink =page.getByRole('link', { name: 'Accounts Overview' });
    }

    async openNewAccount(accountType = 'SAVINGS'): Promise<string> {
        await this.openAccountLink.click();
        await this.page.waitForURL(/openaccount\.htm/);

        // ParaBank renders the form before asynchronously loading source accounts.
        await this.page.waitForLoadState('networkidle', { timeout: 10000 }).catch(() => undefined);
        await expect(this.accountType).toBeVisible({ timeout: 15000 });
        await expect(this.fromAccount).toBeVisible({ timeout: 15000 });
        await this.accountType.selectOption({ label: accountType });

        // Opening an account requires an existing account to fund the initial deposit.
        await expect(this.fromAccount.locator('option[value]:not([value=""])')).not.toHaveCount(0, { timeout: 15000 });
        await this.fromAccount.selectOption({ index: 0 });
        await this.openAccountButton.click({ noWaitAfter: true });
        await expect(this.accountsuccessMessage).toBeVisible();

        // The account ID is generated by ParaBank and changes on every run.
        const accountNumberText = (await this.accountNumber.textContent())?.trim();
        if (!accountNumberText) {
            throw new Error('Account opened successfully but no account number was displayed');
        }

        console.log("New account number: " + accountNumberText);
        await this.accountoverviewLink.click({ noWaitAfter: true });
        await expect(this.page.getByRole('heading', { name: 'Accounts Overview' })).toBeVisible();
        return accountNumberText;
    }

    async getAccountBalance(accountNumber: string): Promise<number> {
        const accountLink = this.page.getByRole('link', { name: accountNumber, exact: true });
        const accountRow = accountLink.locator('xpath=ancestor::tr');
        await expect(accountLink).toBeVisible({ timeout: 15000 });

        // Parse the Balance column so currency formatting does not affect the assertion.
        const balanceText = await accountRow.locator('td').nth(1).innerText();
        const balance = Number(balanceText.replace(/[^\d.-]/g, ''));
        if (!Number.isFinite(balance)) {
            throw new Error(`Could not parse opening balance for account ${accountNumber}: ${balanceText}`);
        }
        return balance;
    }


}